### ISSUE TITLE
How to use over9000 in common pytorch code?

### ISSUE THREAD

**Issue by askerlee** [mgrankin/over9000#1]
Thanks for the code. However I'm not familiar with fast.ai, so I'm not sure how to replace other optimizers with over9000. Could you please provide an Optimizer interface? Thank you very much.

**Comment by pabloppp** [comment]
AFAIK you can just import it and use it as any other PyTorch optimizer:

```
from over900 import Over9000

optimizer = Over9000(model.parameters())
```

**Comment by askerlee** [comment]
Thank you @pabloppp !
Just realized Over9000() returns an optimizer object...

**Comment by askerlee** [comment]
Have made it working. However based on the first dozens of iterations, the performance seems to be much worse than ranger or novograd... Tried two different initial learning rates and neither had close performance as those two optimizers. Currently not having enough time to dig deeper so I would stop here.

**Comment by mgrankin** [comment]
I've introduced a bug today, now reversed. You can try it now.

**Comment by redknightlois** [comment]
@askerlee There was a bug in the code, apparently on some datasets it was good, but on others, it behaves erratically. Today's update to Ralamb impact RangerLars (Over9000), so would be great to have your input on it.

**Comment by burgalon** [comment]
i'm getting an error 
```
AttributeError: 'Lookahead' object has no attribute 'state'
```

not sure what's the reason for that

**Comment by askerlee** [comment]
@redknightlois @mgrankin Thanks for the update. I've tried and it still performs worse than ranger. The reason may be that my task is a bit untypical.

**Comment by mgrankin** [comment]
>AttributeError: 'Lookahead' object has no attribute 'state'

@burgalon It really doesn't have that attribute. What is the code that gives you that error?

**Comment by mgrankin** [comment]
> i'm getting an error
> 
> ```
> AttributeError: 'Lookahead' object has no attribute 'state'
> ```
> 
> not sure what's the reason for that

Discussion here #6

**Comment by mgrankin** [comment]
@burgalon you can try it now.

**Comment by askerlee** [comment]
Now seems over9000 (RangerLars) works pretty well 👍 Better than ranger on my first experiment
