### ISSUE TITLE
What is the meaning of Imagenette and Imagewoof ?

### ISSUE THREAD

**Issue by fyting** [mgrankin/over9000#14]

**Comment by mgrankin** [comment]
Imagenet is expensive to train if you are not Google or Amazon and you'r trying to test several hypothesis. So, Jeremy Howard (fast.ai) came up with this two subsets of the original Imagenet.

**Comment by fyting** [comment]
> Imagenet is expensive to train if you are not Google or Amazon and you'r trying to test several hypothesis. So, Jeremy Howard (fast.ai) came up with this two subsets of the original Imagenet.

Thanks
