### ISSUE TITLE
Recommendation on optimal LR

### ISSUE THREAD

**Issue by IamGianluca** [mgrankin/over9000#22]
Hi, 

I've been playing around with over9000 and I can confirm it works really well. Do you have any recommendations regarding how to find the optimal LR? I tried to use the LR finder we generally use for the OneCycleLR policy but it seems the recommended LR is a little too high. The model can make rapid progress in the first couple of epochs but valid AUC oscillates a lot.

Below is a comparison between over9000 using the LR recommended by the LR finder and using 60 % flat + cosine annealing (blue) and the LR I found manually by trial and error (orange). The LR recommended was always between 0.005 and 0.004, whereas the LR I found manually was 0.001.

![image](https://user-images.githubusercontent.com/4025968/89074126-ccc8b380-d349-11ea-9cea-73e324418bc2.png)

The 5 main drops in AUC are due to restarting the model ― I'm running 5-fold cross-validation (10 epochs per fold).

I've tried to increase decrease the annealing from 40% to 80% but when using such a high LR, 60% seems to work best. 

Have you found a good heuristic to set the initial LR that works well in practice?

**Comment by mgrankin** [comment]
Hi,

Typically I play around values provided by LR finder. I can confirm that LR finder often suggest too high LR, but I don't know any better heuristic.

**Comment by IamGianluca** [comment]
Got it! Thank you for sharing your experience @mgrankin
