### ISSUE TITLE
Performance mismatch between notebook and readme

### ISSUE THREAD

**Issue by juntang-zhuang** [mgrankin/over9000#24]
Hi, I noticed that there's a performance mismatch between readme and the notebook. The accuracy in notebook (just as it is when uploaded, I did not perform any re-training) is overall lower than readme, for imagenette, for example, RangerLARS in notebook is "mean = 0.7506984382867813, std = 0.00592458289260687, ci-95 = (0.7478536156223473, 0.7535432609512153)", while readme reported around 87%, has anything been changed? Somehow I suspect if the dataset from fastai has been changed, or the model, or metrics? Thanks a lot.

**Comment by mgrankin** [comment]
Hello, fastai changed the dataset between v1 and v2, that's why the mismatch. I should update readme.

**Comment by juntang-zhuang** [comment]
Thanks a lot for clarification.
